### ISSUE TITLE
crontab 进程

### ISSUE THREAD

**Issue by icellus** [walkor/crontab#1]
请问这个定时任务是单进程,会造成阻塞的吗？
如果有多个crontab想要从数据库取出配置，并且可以独立不造成阻塞 怎么做必要好。

**Comment by walkor** [comment]
是否阻塞和单进程多进程没有必然联系。是否阻塞和业务代码有关，并且阻塞不代表一定会影响业务。比如每隔一分钟获取数据中某个数据，使用阻塞和非阻塞读数据库对于业务来说没有区别。至于你说的怎么做才好，还是看你的具体业务。

**Comment by icellus** [comment]
嗯，主要是担心有些耗时较长的任务会阻塞其他任务。
而且代码出错的话，可能会导致多个任务都无法正常执行。

**Comment by walkor** [comment]
如果担心就测试下，如果确实出现任务耗时超过定时间隔，就想办法把任务分解为多进程的定时任务，或者想办法让业务处理更快。

业务代码出错这问题没什么好说的，框架没办法智能到给你解决任何报错，代码质量需要自己保证。
