### ISSUE TITLE
定时器执行问题

### ISSUE THREAD

**Issue by cshaptx4869** [walkor/crontab#10]
1.0.4 版本开始，下一秒就开始执行定时任务。
但是发现有问题，到下一分钟执行频率乱套了，场景复现如下：
代码：
[https://foruda.gitee.com/images/1673683751262076072/c5e83612_5507348.jpeg](https://foruda.gitee.com/images/1673683751262076072/c5e83612_5507348.jpeg
)
执行记录：
[https://foruda.gitee.com/images/1673683815022015587/9ae2e73b_5507348.jpeg](https://foruda.gitee.com/images/1673683815022015587/9ae2e73b_5507348.jpeg)

**Comment by walkor** [comment]
使用目前最新版本 1.0.6试下

**Comment by cshaptx4869** [comment]
> 使用目前最新版本 1.0.6试下

奥… 阿里云镜像最新版只有1.04 取消镜像下载最新的1.06版本就恢复正常了 和原来一样是下一分钟执行 感谢😊
