### ISSUE TITLE
Crontab 是否是堵塞的

### ISSUE THREAD

**Issue by cshaptx4869** [walkor/crontab#11]
`new Crontab()`

- 第一个参数，执行频率设置的是 */1 * * * * * （每秒执行）
- 第二个参数，执行了一个比较耗时的任务（假设执行耗时时间是 20 秒）

那么从执行的测试结果上来看，好像是堵塞的，并不会按执行频率定时执行。
[https://foruda.gitee.com/images/1673853265699053939/f1da68b8_5507348.jpeg](https://foruda.gitee.com/images/1673853265699053939/f1da68b8_5507348.jpeg)

**Comment by walkor** [comment]
workerman不会改变php原有特性，如果里面任务是调用了阻塞的函数或方法例如pdo_mysql redis扩展等那就是阻塞的。

**Comment by cshaptx4869** [comment]
> workerman不会改变php原有特性，如果里面任务是调用了阻塞的函数或方法例如pdo_mysql redis扩展等那就是阻塞的。

感谢解答
