### ISSUE TITLE
使用php8.2 启用定时器，microtime(true)会出现Implicit conversion from float to int loses precision警告

### ISSUE THREAD

**Issue by php2py** [walkor/crontab#13]
目前我是在这个文件的`vendor\workerman\workerman\Events\Select.php`    267行，强制转换了整形，不知道会出现什么影响，麻烦老大帮忙看看

![1695094372415](https://github.com/walkor/crontab/assets/42958693/76715beb-3dda-4541-abbb-2fc95da667f9)

**Comment by walkor** [comment]
以后遇到类似兼容问题先升级workerman




walkor
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "walkor/crontab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 中午11:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[walkor/crontab] 使用php8.2 启用定时器，microtime(true)会出现Implicit conversion from float to int loses precision警告 (Issue #13)





 
目前我是在这个文件的vendor\workerman\workerman\Events\Select.php    267行，强制转换了整形，不知道会出现什么影响，麻烦老大帮忙看看

**Comment by php2py** [comment]
好的，谢谢老大，刚才发现了，Workerman\Crontab\Crontab已经升级到1.0.6了
