### ISSUE TITLE
php版本问题

### ISSUE THREAD

**Issue by thinker-gao** [walkor/crontab#2]
1.composer.json中标记为"php": ">=5.4"即可，导致php版本5.6 5.4 5.5可以直接安装，而您写的start.php会报错，因为crontab的解析类语法是>=7.0  例如 string  xxx int xxx      function():bool
2.如果要是只支持7.0，那么需要修改composer.json   ，如果需要支持>=5.4，还需要修改，我看到这个问题，不知道应该如何修复并提交上来

**Comment by walkor** [comment]
感谢反馈。已改composer PHP >=7.0

**Comment by walkor** [comment]
感谢反馈。已改composer PHP >=7.0

**Comment by walkor** [comment]
感谢反馈。已改composer PHP >=7.0
