### ISSUE TITLE
请解惑一下，这是php进程阻塞引起的吗，不支持异步执行多个任务吗？

### ISSUE THREAD

**Issue by wdwlrz** [walkor/crontab#5]
new两个Crontab() ，第一个每分钟第一秒执行，第二个每分钟第二秒执行，如果第一个执行sleep70秒，那么在第五秒的时候好像触发不到第二个任务，或者说，触发了，但是没能执行到，要等70秒后才会执行。这是Windows下php的问题吗？

$worker->onWorkerStart = function () {
    // Execute the function in the first second of every minute.
    new Crontab('1 * * * * *', function(){
        echo "[1]start:".date('Y-m-d H:i:s')."\n";
        sleep(70);
        echo "[1]end:".date('Y-m-d H:i:s')."\n";
    });
    new Crontab('2 * * * * *', function(){
        echo "[2]start:".date('Y-m-d H:i:s')."\n";
        sleep(70);
        echo "[2]end:".date('Y-m-d H:i:s')."\n";
    });
};

运行：
[1]start:2022-07-02 17:15:01
[1]end:2022-07-02 17:16:11
[2]start:2022-07-02 17:16:11
[2]end:2022-07-02 17:17:21

**Comment by walkor** [comment]
对，阻塞引起的。使用阻塞函数类似sleep这种就会阻塞进程。你可以把慢任务单独放到一组进程里去执行，避免互相影响
